/// Language object with name and code (ISO)
class Language {
  final String name;
  final String code;

  Language(this.code, this.name);

  @override
  String toString() => name;
}

/// Language list containing all languages supported by Google Translate API
class LanguageList {
  static final _langs = {
    'auto': 'Automatic',
    "ab": "Abkhaz",
    "ace": "Acehnese",
    "ach": "Acholi",
    "aa": "Afar",
    "af": "Afrikaans",
    "sq": "Albanian",
    "alz": "Alur",
    "am": "Amharic",
    "ar": "Arabic",
    "hy": "Armenian",
    "as": "Assamese",
    "av": "Avar",
    "awa": "Awadhi",
    "ay": "Aymara",
    "az": "Azerbaijani",
    "ban": "Balinese",
    "bal": "Baluchi",
    "bm": "Bambara",
    "bci": "Baoulé",
    "ba": "Bashkir",
    "eu": "Basque",
    "btx": "Batak Karo",
    "bts": "Batak Simalungun",
    "bbc": "Batak Toba",
    "be": "Belarusian",
    "bem": "Bemba",
    "bn": "Bengali",
    "bew": "Betawi",
    "bho": "Bhojpuri",
    "bik": "Bikol",
    "bs": "Bosnian",
    "br": "Breton",
    "bg": "Bulgarian",
    "bua": "Buryat",
    "yue": "Cantonese",
    "ca": "Catalan",
    "ceb": "Cebuano",
    "ch": "Chamorro",
    "ce": "Chechen",
    "ny": "Chichewa",
    "zh-cn": "Chinese (Simplified)",
    "zh-tw": "Chinese (Traditional)",
    "chk": "Chuukese",
    "cv": "Chuvash",
    "co": "Corsican",
    "crh": "Crimean Tatar (Cyrillic)",
    "crh-latn": "Crimean Tatar (Latin)",
    "hr": "Croatian",
    "cs": "Czech",
    "da": "Danish",
    "fa-af": "Dari",
    "dv": "Dhivehi",
    "din": "Dinka",
    "doi": "Dogri",
    "dov": "Dombe",
    "nl": "Dutch",
    "dyu": "Dyula",
    "dz": "Dzongkha",
    "en": "English",
    "eo": "Esperanto",
    "et": "Estonian",
    "ee": "Ewe",
    "fo": "Faroese",
    "fj": "Fijian",
    "tl": "Filipino",
    "fi": "Finnish",
    "fon": "Fon",
    "fr": "French",
    "fr-ca": "French (Canada)",
    "fy": "Frisian",
    "fur": "Friulian",
    "ff": "Fulani",
    "gaa": "Ga",
    "gl": "Galician",
    "ka": "Georgian",
    "de": "German",
    "el": "Greek",
    "gn": "Guarani",
    "gu": "Gujarati",
    "ht": "Haitian Creole",
    "cnh": "Hakha Chin",
    "ha": "Hausa",
    "haw": "Hawaiian",
    "iw": "Hebrew",
    "hil": "Hiligaynon",
    "hi": "Hindi",
    "hmn": "Hmong",
    "hu": "Hungarian",
    "hrx": "Hunsrik",
    "iba": "Iban",
    "is": "Icelandic",
    "ig": "Igbo",
    "ilo": "Ilocano",
    "id": "Indonesian",
    "iu-latn": "Inuktut (Latin)",
    "iu": "Inuktut (Syllabics)",
    "ga": "Irish",
    "it": "Italian",
    "jam": "Jamaican Patois",
    "ja": "Japanese",
    "jw": "Javanese",
    "kac": "Jingpo",
    "kl": "Kalaallisut",
    "kn": "Kannada",
    "kr": "Kanuri",
    "pam": "Kapampangan",
    "kk": "Kazakh",
    "kha": "Khasi",
    "km": "Khmer",
    "cgg": "Kiga",
    "kg": "Kikongo",
    "rw": "Kinyarwanda",
    "ktu": "Kituba",
    "trp": "Kokborok",
    "kv": "Komi",
    "gom": "Konkani",
    "ko": "Korean",
    "kri": "Krio",
    "ku": "Kurdish (Kurmanji)",
    "ckb": "Kurdish (Sorani)",
    "ky": "Kyrgyz",
    "lo": "Lao",
    "ltg": "Latgalian",
    "la": "Latin",
    "lv": "Latvian",
    "lij": "Ligurian",
    "li": "Limburgish",
    "ln": "Lingala",
    "lt": "Lithuanian",
    "lmo": "Lombard",
    "lg": "Luganda",
    "luo": "Luo",
    "lb": "Luxembourgish",
    "mk": "Macedonian",
    "mad": "Madurese",
    "mai": "Maithili",
    "mak": "Makassar",
    "mg": "Malagasy",
    "ms": "Malay",
    "ms-arab": "Malay (Jawi)",
    "ml": "Malayalam",
    "mt": "Maltese",
    "mam": "Mam",
    "gv": "Manx",
    "mi": "Maori",
    "mr": "Marathi",
    "mh": "Marshallese",
    "mwr": "Marwadi",
    "mfe": "Mauritian Creole",
    "chm": "Meadow Mari",
    "mni-mtei": "Meiteilon (Manipuri)",
    "min": "Minang",
    "lus": "Mizo",
    "mn": "Mongolian",
    "my": "Myanmar (Burmese)",
    "nhe": "Nahuatl (Eastern Huasteca)",
    "ndc-zw": "Ndau",
    "nr": "Ndebele (South)",
    "new": "Nepalbhasa (Newari)",
    "ne": "Nepali",
    "bm-nkoo": "NKo",
    "no": "Norwegian",
    "nus": "Nuer",
    "oc": "Occitan",
    "or": "Odia (Oriya)",
    "om": "Oromo",
    "os": "Ossetian",
    "pag": "Pangasinan",
    "pap": "Papiamento",
    "ps": "Pashto",
    "fa": "Persian",
    "pl": "Polish",
    "pt": "Portuguese",
    "pa": "Punjabi (Gurmukhi)",
    "pa-arab": "Punjabi (Shahmukhi)",
    "qu": "Quechua",
    "kek": "Qʼeqchiʼ",
    "rom": "Romani",
    "ro": "Romanian",
    "rn": "Rundi",
    "ru": "Russian",
    "se": "Sami (North)",
    "sm": "Samoan",
    "sg": "Sango",
    "sa": "Sanskrit",
    "sat-latn": "Santali (Latin)",
    "sat": "Santali (Ol Chiki)",
    "gd": "Scots Gaelic",
    "nso": "Sepedi",
    "sr": "Serbian",
    "st": "Sesotho",
    "crs": "Seychellois Creole",
    "shn": "Shan",
    "sn": "Shona",
    "scn": "Sicilian",
    "szl": "Silesian",
    "sd": "Sindhi",
    "si": "Sinhala",
    "sk": "Slovak",
    "sl": "Slovenian",
    "so": "Somali",
    "es": "Spanish",
    "su": "Sundanese",
    "sus": "Susu",
    "sw": "Swahili",
    "ss": "Swati",
    "sv": "Swedish",
    "ty": "Tahitian",
    "tg": "Tajik",
    "ber-latn": "Tamazight",
    "ber": "Tamazight (Tifinagh)",
    "ta": "Tamil",
    "tt": "Tatar",
    "te": "Telugu",
    "tet": "Tetum",
    "th": "Thai",
    "bo": "Tibetan",
    "ti": "Tigrinya",
    "tiv": "Tiv",
    "tpi": "Tok Pisin",
    "to": "Tongan",
    "lua": "Tshiluba",
    "ts": "Tsonga",
    "tn": "Tswana",
    "tcy": "Tulu",
    "tum": "Tumbuka",
    "tr": "Turkish",
    "tk": "Turkmen",
    "tyv": "Tuvan",
    "ak": "Twi",
    "udm": "Udmurt",
    "uk": "Ukrainian",
    "ur": "Urdu",
    "ug": "Uyghur",
    "uz": "Uzbek",
    "ve": "Venda",
    "vec": "Venetian",
    "vi": "Vietnamese",
    "war": "Waray",
    "cy": "Welsh",
    "wo": "Wolof",
    "xh": "Xhosa",
    "sah": "Yakut",
    "yi": "Yiddish",
    "yo": "Yoruba",
    "yua": "Yucatec Maya",
    "zap": "Zapotec",
    "zu": "Zulu",
  };

  Language operator [](String code) {
    code = code.toLowerCase();
    if (_langs.containsKey(code)) {
      return Language(code, _langs[code]!);
    }
    throw LanguageNotSupportedException('$code is not a supported language.');
  }

  static bool contains(String codeOrLang) {
    if (_langs.containsKey(codeOrLang) ||
        _langs.containsValue(codeOrLang.toCamelCase())) {
      return true;
    }
    return false;
  }
}

class LanguageNotSupportedException implements Exception {
  final String msg;
  LanguageNotSupportedException(String lang)
      : msg = '$lang is not a supported language.';
}

extension _CamelCase on String {
  String toCamelCase() {
    return '${this[0].toUpperCase()}${this.substring(1).toLowerCase()}';
  }
}
